-- =============================================
-- Clothing Store - Supabase Schema
-- Run this in Supabase SQL Editor
-- =============================================

-- PRODUCTS TABLE
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  "Category" text,
  "Price" integer,
  "Description" text,
  "Image" text,
  "Quantity" integer default 0,
  created_at timestamptz default now()
);

-- ENUM TYPE FOR ROLE
create type user_role as enum ('admin', 'user');

-- USERS TABLE
create table if not exists users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null,
  name text not null,
  phone text,
  role user_role default 'user',
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- CART TABLE
create table if not exists cart (
  id bigint generated by default as identity primary key,
  user_id text not null,
  product_id integer not null,
  product_name text,
  product_price integer,
  product_category text,
  product_image text,
  quantity integer default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ORDERS TABLE
create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  customer_name text,
  customer_email text,
  customer_phone text,
  address text,
  city text,
  state text,
  pincode text,
  country text,
  order_items jsonb,
  total_items integer,
  total_price integer,
  status text default 'Confirmed',
  shipping_id text,
  shipping_company text,
  order_date timestamptz default now(),
  updated_at timestamptz default now()
);

-- =============================================
-- Row Level Security (RLS) - Optional but recommended
-- =============================================

-- Disable RLS for service role (backend uses service role key)
-- These are already bypassed by service role key, but good to document

-- Enable RLS on tables (optional - service role bypasses this)
-- alter table products enable row level security;
-- alter table users enable row level security;
-- alter table cart enable row level security;
-- alter table orders enable row level security;
